[gravity]
host = "0.0.0.0:32803"

[subscriber]
subscriber_id = "rest_exporter"
subscriber_name = "REST Exporter"
state_store = "./statestore"
worker_count = 4
verbose = true

[rules]
subscription = "./settings/subscriptions.json"

