[gravity]
domain = "gravity"
host = "0.0.0.0:32803"

[subscriber]
subscriberID = "rest_exporter"
subscriberName = "REST Exporter"
stateStore = "./statestore"
workerCount = 4
verbose = true
pipelineStart = 0
pipelineEnd = -1

[rules]
subscription = "./settings/subscriptions.json"

